DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NTAzNjE1NDcsInVzZXJJZCI6Mn0.f1CGvuWxzSpMuQ9ngJ-pSiCzNCyUiEnmRWdfg-hzD28