DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI2QGV4YW1wbGUuY29tIiwiZXhwIjoxNzUwOTY4ODI2LCJ1c2VySWQiOjExN30.Km2bzjse_RRvO9waXcCu6RlQ27kGphkn1Ur8OvAS51c