POST http://localhost:8080/events
content-type: application/json
authorization: replace with the token you will get from Login either through REST Client,Frontend or CURL

{
  "name": "Test event33",
  "description": "Test event!!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
