POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI2QGV4YW1wbGUuY29tIiwiZXhwIjoxNzUwOTY4ODI2LCJ1c2VySWQiOjExN30.Km2bzjse_RRvO9waXcCu6RlQ27kGphkn1Ur8OvAS51c

{
  "name": "Test event37",
  "description": "Test event!!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
